version: "3"

services:
  webapp:
    image: dockercompose/dockercompose:0.0.1-SNAPSHOT
    ports:
      - "8088:8088"
    volumes:
      - "/home/dockercomposetest/"
      #depends_on:
      #- redis
    #- mysql

  #redis:
    # image: redis:latest
    #restart: always
      # ports:
    #  - "6389:6379"
      # volumes:
    #   - /redis/redis.conf:/etc/redis/redis.conf
    # command: redis-server /etc/redis/redis.conf

    #mysql:
    #image: mysql:5.7
    # restart: always
      #environment:
      #MYSQL_ROOT_PASSWORD: "root"
      #MYSQL_USER: 'root'
      # MYSQL_PASS: 'root'
      #ports:
      #- "3306:3306"
      #volumes:
      # - "./db:/var/lib/mysql"
      # - "./conf/my.cnf:/etc/my.cnf"
      # - "./init:/docker-entrypoint-initdb.d/"
