server:
  port: 8089

spring:
  #rabbitmq:
    #host: 129.28.158.68
    #port: 5672
    #username: zhouchao
    #password: 123456
    #消息发送确认回调
    #publisher-confirms: true
    #确认消息已发送到队列(Queue)
    #publisher-returns: true
  datasource:
    username: root
    password: root
    url: jdbc:mysql://129.28.158.68:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 20
    minIdle: 30
    maxActive: 50
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat
    connectionProperties:
      druid:
        stat:
          slowSqlMillis: 5000
  #data:
    #solr:
      #host: http://129.28.158.68:8983/solr

docker:
  image:
    prefix: mybatis-plustest_1.0

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zc.mybatisplustest.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
